        <tr><td colspan="3" nowrap>&nbsp;</td></tr>
        <tr>
		 <td colspan="3" nowrap>
          <table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#6C6C6C">
           <tr><td class="nhbg" width=1% align="center" valign="middle">Player Name</td><td class="shbg" align="center" width=1%>KILLS</td><td class="shbg" align="center" width=1%>DEATHS</td><td class="shbg" align="center" width=1%>SPECIALS</td></tr>
           <%StatRows%>
          </table>
         </td>
        <tr>
